
/**:
  ros__parameters:
    planning_pipelines: ["ompl", "pilz"]
    capabilities: >-
        move_group/MoveGroupExecuteTrajectoryAction
        pilz_industrial_motion_planner/MoveGroupSequenceAction
        pilz_industrial_motion_planner/MoveGroupSequenceService
        move_group/TfPublisher
    # Trajectory execution manager parameters
    allow_trajectory_execution: true
    moveit_manage_controllers: false
    trajectory_execution:
      allowed_execution_duration_scaling: 1.2
      allowed_goal_duration_margin: 0.5
      allowed_start_tolerance: 0.01
    # Planning scene monitor parameters
    publish_planning_scene: true
    publish_geometry_updates: true
    publish_state_updates: true
    publish_transforms_updates: true
    planning_scene_tf_prefix: ""
